# Generated by Django 3.0.1 on 2019-12-29 13:19

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0002_income'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='income',
            new_name='Incomme',
        ),
    ]
