# Generated by Django 3.0.1 on 2019-12-29 13:25

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('web', '0003_auto_20191229_1649'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Incomme',
            new_name='Income',
        ),
    ]
